[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[[profile.default.fs_permissions]]
access = "read"
path = "./testdata"

[dependencies]
"@openzeppelin-contracts" = "5.0.1"
forge-std = "1.9.4"
vlayer = "0.2.0-nightly-20250418-78a78bc160c786d9970ecf0704a9bfa7a0447bf7"

[dependencies.risc0-ethereum]
version = "2.0.0"
url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v2.0.0-soldeer/contracts.zip"

[soldeer]
remappings_generate = false
remappings_regenerate = false

[[soldeer.fs_permissions]]
access = "read"
path = "./testdata"
fs_permissions = [{ access = "read", path = "./testdata"}]

